spring:
  profiles:
    active: dev

  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5433/pgsdb
    username: pgsuser
    password: pgspw

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true

  output.ansi.enabled: always

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    default-schema: public

products:
  products-base-url: "http://localhost:${sever.port}/api/products"
  http:
    connect-timeout-ms: 1500
    read-timeout-ms: 2500

limits:
  default: 10000.00

resilience4j:
  retry:
    instances:
      products:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
  circuitbreaker:
    instances:
      products:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080
